Sportsmandu/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using AutoMapper;
using HashidsNet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sportsmandu.Data;
using Sportsmandu.Model.Club.ViewModels;
using Sportsmandu.Model.Entities.ViewModels;
using Sportsmandu.Models;
using Sportsmandu.Models.Generic;
using Sportsmandu.Models.League;
using Sportsmandu.Services.Abstract;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using static Sportsmandu.Models.SportsmanduImage;
using Microsoft.Extensions.Caching.Memory;
using Sportsmandu.Model.Entities.Globalization;
using Sportsmandu.Models.Association;
namespace Sportsmandu.Controllers
{
    public class GameController : Controller
    {
        AppDbContext _context;
        IMapper _mapper;
        private IMemoryCache _cache;
        private IBlogService _blogService;
        Sportsmandu.Services.IEmailSender _emailSender;
        public GameController(IMemoryCache _cache, AppDbContext _context, IMapper _mapper, IBlogService _blogService, Sportsmandu.Services.IEmailSender _emailSender)
        {
            this._cache = _cache;
            this._blogService = _blogService;
            this._context = _context;
            this._mapper = _mapper;
            this._emailSender = _emailSender;
        }
        public dynamic CreateStructuresForStats(int CategoryId = 1)
        {
            StatsDB stats = new StatsDB();
            stats.CategoryId = CategoryId;
            return stats;
        }
        public IActionResult Alexa(string culture,string id)
        {
            SetSiteSectionLanguagetitle(culture, "layout");
            SetSiteSectionLanguagetitle(culture, "alexa");
            var alexaRank = _context.Alexa.OrderBy(x => x.Date).Where(x=>x.WebsiteName == id).ToList();
            return View(alexaRank);
        }
        public IActionResult Key(string culture)
        {
            return View();
        }
        public GenericResult ProcessPredictions()
        {
            var PredictionsForMatch = _context.Predict.ToList();
            return new GenericResult();
            //if (ccvm.Status == enumTeamFixtureStatus.Won || ccvm.Status == enumTeamFixtureStatus.Lost)
            //    //Below is for Game Winning Tosses
            //    foreach (var Predictions in PredictionsForMatch.Where(x => x.TeamId != null).Where(x => x.TeamId == ccvm.ClubId))
            //    {
            //        if (Predictions.Prediction == enumFixturePredict.Win)
            //        {
            //            if (ccvm.Status == enumTeamFixtureStatus.Won)
            //            {
            //                Predictions.PredictionSucceded = true;
            //                Predictions.Result = PredictionResult.Correct;
            //            }
            //            else
            //            {
            //                Predictions.PredictionSucceded = false;
            //                Predictions.Result = PredictionResult.Prediction_Failed;
            //            }
            //        }
            //        else if (ccvm.Status == enumTeamFixtureStatus.Lost)
            //        {
            //            if (ccvm.Status == enumTeamFixtureStatus.Lost)
            //            {
            //                Predictions.PredictionSucceded = true;
            //                Predictions.Result = PredictionResult.Correct;
            //            }
            //            else
            //            {
            //                Predictions.PredictionSucceded = false;
            //                Predictions.Result = PredictionResult.Prediction_Failed;
            //            }
            //        }
            //        _context.Entry(Predictions).State = EntityState.Modified;
            //    }


            foreach (var Predictions in PredictionsForMatch.Where(x => x.TeamId == null))
            {
                if (Predictions.Prediction == enumFixturePredict.Draw)
                {                    
                        Predictions.PredictionSucceded = true;
                        Predictions.Result = PredictionResult.Correct;                                        
                        _context.Entry(Predictions).State = EntityState.Modified;
                }
            }
            _context.SaveChanges();
        }
        public IActionResult Predictions(string Culture)
        {
            SetSiteSectionLanguagetitle(Culture, "layout");
            SetSiteSectionLanguagetitle(Culture, "prediction");
            List<PredictionVMFORES> predictions = new List<PredictionVMFORES>();           
            var users = _context.Users
                .Include(x => x.Predictions)
                .Include(x=>x.Roles)                
                //.OrderByDescending(x=>x.Predictions.Count())
                .ToList();
            List<ApplicationUserVMFORES> topPredictionsToSend = users.Adapt<List<ApplicationUserVMFORES>>();
            ViewBag.TopPredictions = topPredictionsToSend.OrderByDescending(x=>x.Successed_Predictions_Count).Take(5).ToList();
            SetMatch(Culture, 8, "Matches", true);
                SetMyPredictions(Culture);
            return View();
        }
        private void SetMyPredictions(string Culture)
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.MyPredictions = Sportsmandu.Api.Controllers.ProductController.GetPredictions(Culture, User.Identity.Name,_cache).Adapt<List<PredictionVMFORES>>();
            }
        }
        //static IEnumerable<T> Randomize<T>(this IEnumerable<T> source)
        //{
        //    var array = source.ToArray();
        //    // randomize indexes (several approaches are possible)
        //    return array;
        //}
        //[Authorize]
        public IActionResult FBPredictions(string Culture)
        {
            SetSiteSectionLanguagetitle(Culture, "layout");
            SetSiteSectionLanguagetitle(Culture, "prediction");            
            List<PredictionVMFORES> predictions = new List<PredictionVMFORES>();
            var users = _context.Users
                .Include(x => x.Predictions)
                .Include(x=>x.Roles)                
                .ToList();
            if (User.Identity.IsAuthenticated)
            {                
                ViewBag.MyImage = users.Where(x => x.Email == User.Identity.Name).SingleOrDefault().Avatar;
            }
            List<ApplicationUserVMFORES> topPredictionsToSend = users.Adapt<List<ApplicationUserVMFORES>>();
            var topPredictions = topPredictionsToSend.OrderByDescending(x=>x.Successed_Predictions_Count).Take(20).ToList();
            foreach(var items in topPredictions)
            {
                if(items.Avatar == null)
                {
                    items.Avatar = "/images/users/no_profile.jpg";
                }
            }
            ViewBag.TopPredictions = topPredictions;
            SetMatch(Culture, 6, "Matches",true);
            SetMyPredictions(Culture);
            return View();
        }
       public IActionResult Construction(string Culture)
        {
            SetSiteSectionLanguagetitle(Culture, "construction_page");
            return View();
        }
        public void SetSiteSectionLanguagetitle(string Culture,string section)
        {
            List<SiteSectionLanguageTitleForEs> siteSectionLanguageTitle = Sportsmandu.Api.Controllers.ProductController.SiteSectionLanguageTitle(Culture, section, _cache).ToList();
            foreach (var items in siteSectionLanguageTitle)
            {
                this.HttpContext.Items[items.LanguageTitleName] = items.LanguageTitleGlobalizations.Where(x => x.CultureCode == Culture).SingleOrDefault().Value;
            }
        }
        public IActionResult Index(string Culture,string Id)
        {
            var gamesTosend = _context.Games.Include(x => x.Culture).ToList();
            var gameTosend = gamesTosend.Where(x=>x.Guid == Id).FirstOrDefault().Adapt<GameViewModel>();
            var highScores = _context.ApplicationUserGames
                .Include(x => x.User)
                .Where(x => x.GameId == gameTosend.Id);

            if(gameTosend.Type == enumGameType.High_Score)
            {
                highScores = highScores.OrderByDescending(x => x.HighScore)
                .Take(5);
            }else if (gameTosend.Type == enumGameType.Level)
            {
                highScores = highScores.OrderByDescending(x => x.Level)
                    .Take(5);
            }
            else if (gameTosend.Type == enumGameType.Points)
            {
                highScores = highScores.OrderByDescending(x => x.Points)
                    .Take(5);
            }
            gameTosend.HighScore = highScores.Adapt<List<ScoreViewModel>>();
            //string gameHtml = System.IO.File.ReadAllText("wwwroot/games/" + gameTosend.FolderUrl + "/" + "PlayMe.html");
            //ViewBag.GameHtml = gameHtml;
            return View(gameTosend);
        }

        [Authorize]
        public IActionResult PlayGame(string Culture, string Id)
        {
            var gamesTosend = _context.Games.Include(x=>x.Culture).ToList();
            var gameTosend = gamesTosend.FirstOrDefault().Adapt<GameViewModel>();
            var highScores = _context.ApplicationUserGames
                .Include(x => x.User)
                .OrderByDescending(x => x.HighScore)
                .Where(x => x.GameId == gameTosend.Id)
                .Take(5);
            gameTosend.HighScore = highScores.Adapt<List<ScoreViewModel>>();
            string gameHtml = System.IO.File.ReadAllText("wwwroot/games/" + gameTosend.FolderUrl + "/" + "PlayMe.html");
            ViewBag.GameHtml = gameHtml;

            var user = _context.Users.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            var hashids = new Hashids(gameTosend.Guid);

Sportsmandu/ViewComponents/AdsViewComponent.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Sportsmandu.Model.Entities.Ground;
using System;
using System.Collections.Generic;
using System.Linq;
namespace Sportsmandu.ViewComponents
{
    [AllowAnonymous]
    public class AdsViewComponent : ViewComponent
    {
        IMemoryCache _cache;

        public AdsViewComponent(IMemoryCache cache)
        {
            _cache = cache;
        }
        public IViewComponentResult Invoke()
        {
            if (this.RouteData.Values["area"] != null && this.RouteData.Values["area"] == "Admin") return View();
            string Culture = this.RouteData.Values["culture"] != null ? this.RouteData.Values["culture"].ToString() : null;
            Culture = Culture == "1" ? Culture = "En" : Culture;
            Culture = Culture == "2" ? Culture = "Np" : Culture;
            if (Culture == null)
            {
                //var KKa= this.HttpContext.Response.Cookies;
                var rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
                var culture = rqf.RequestCulture.Culture;
                Culture = culture.Name;
                ;// return View();
            }
            var rqfa = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            var culturea = rqfa.RequestCulture.Culture;
            if (Culture.ToLower() != culturea.Name)
            {
                this.HttpContext.Features.Set<IRequestCultureFeature>(new RequestCultureFeature(new RequestCulture(culture: Culture.ToLower(), uiCulture: Culture.ToLower()), null));
                //SetCurrentThreadCulture(requestCulture)
                this.HttpContext.Response.Cookies.Append(
                    CookieRequestCultureProvider.DefaultCookieName,
                    CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(Culture)),
                    new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
                );
            }
            var _result = Sportsmandu.Api.Controllers.ProductController.SiteSectionLanguageTitle(Culture, "layout",_cache);
            if (_result == null) return View();
            //var KK = this.HttpContext.Response.Cookies;
            foreach (var items in _result)
            {
                try
                {
                    var itsValue = items.LanguageTitleGlobalizations.Where(x => x.CultureCode == Culture).SingleOrDefault();
                    this.HttpContext.Items[items.LanguageTitleName] = itsValue == null ? "ITS NULL" : itsValue.Value;
                }
                catch (Exception) { }
                //ViewData.Add(new KeyValuePair<string, object>(items.LanguageTitleName, items.LanguageTitleGlobalizations
                //            .Where(x => x.CultureCode == Culture).SingleOrDefault().Value));
            }
            //if (this.RouteData.Values["area"] != null && this.RouteData.Values["area"] != "Admin")
            {
                var news = Sportsmandu.Api.Controllers.ProductController.AllBlogPost(Culture,_cache);
                if(news != null)
                {
                    var blogPosts = news.Take(2).ToList();//_context.BlogPosts.Include(x=>x.Culture).OrderByDescending(x => x.PublishDate).Where(x=>x.Culture.Code == Culture).Take(2).ToList();
                    this.HttpContext.Items["Footer_News"] = blogPosts ;
                }
                // var resultTosend = blogPosts.Adapt<List<BlogPostViewModel>>();
            }
            List<GroundVMFORES> venues = Sportsmandu.Api.Controllers.ProductController.GetVenues(Culture).ToList();
            if (venues != null)
            {
                var blogPosts = venues.Where(x=>x.Type == enumVenueType.Venue).Take(8).ToList();//_context.BlogPosts.Include(x=>x.Culture).OrderByDescending(x => x.PublishDate).Where(x=>x.Culture.Code == Culture).Take(2).ToList();
                this.HttpContext.Items["Footer_Venues"] = blogPosts;
            }

            var associations = Sportsmandu.Api.Controllers.ProductController.GetAssociations(Culture);
            this.HttpContext.Items["association_list"] = associations;
            return View();
        }
    }
}

Sportsmandu/Views/Game/Index.cshtml
@using Sportsmandu.Model.Entities.ViewModels;
@model Sportsmandu.Models.GameViewModel;
@{
    ViewData["Title"] = Model.Name;
    ViewData["Title"] = "Play " + @Model.Name + " Online";
    ViewData["OG:Image"] = "https://sportsmandu.com/" + @Model.Image;
    ViewData["og:url"] = "https://sportsmandu.com/En/Game/" + @Model.Id;
    ViewData["og:description"] = @Model.Description;    
}

    <section class="content-info">
        <div class="container paddings-mini">
            <div class="row">
                <div class="col-lg-9">
                    <div class="panel-box">
                        <div class="titles no-margin">
                            <h4>@Model.Name</h4>

                        </div>
                        <div align="center">
                            @*@Html.Raw(ViewBag.GameHtml)*@
                            <a href="~/@Model.URL" target="_blank"><img src="~/@Model.Image" alt=""></a>
                        </div>
                        <div class="row" style="padding-top:15px;padding-bottom:15px">
                            <div class="col-md-6">
                            </div>
                            <div class="col-md-6">
                                <div class="sharethis-inline-share-buttons"></div>
                            </div>
                        </div>
                        <div class="info-panel">
                            @Html.Raw(Model.Description)
                        </div>
                    </div>
                    <div class="panel-box">
                        <div class="titles">
                            <h4>More To Come Soon !</h4>
                        </div>
                        @*<ul class="testimonials">
                                <li>
                                    <blockquote>
                                        <p>Lionel Messi and Cristiano Ronaldo will come face to face for the first time in the World Cup only if their two nations finish in the same position in the group phase, either first or second.!.</p>
                                        <img src="img/testimonials/1.jpg" alt="">
                                        <strong>Federic Gordon</strong><a href="#">@@iwthemes</a>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote>
                                        <p>After two previous meetings on the big stage, it is honours even: Brazil won the Final of Korea/Japan 2002 2-0, while Germany recorded that famous victory at Brazil 2014!.</p>
                                        <img src="img/testimonials/2.jpg" alt="">
                                        <strong>Federic Gordon</strong><a href="#">@@iwthemes</a>
                                    </blockquote>
                                </li>
                                <li>
                                    <blockquote>
                                        <p>To help fire your imagination and let you see if there is a potential knockout match you might be tempted to buy tickets for, FIFA.com has come up with a list of possible last-16 and quarter-final duels between some of the game’s biggest attractions.!.</p>
                                        <img src="img/testimonials/3.jpg" alt="">
                                        <strong>Federic Gordon</strong><a href="#">@@iwthemes</a>
                                    </blockquote>
                                </li>
                            </ul>*@
                    </div>
                    @*<div class="panel-box padding-b">
                        <div class="titles">
                                <h4>Publish Commnet</h4>
                            </div>

                            <div class="info-panel">

                                <form class="form-theme">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Your name *</label>
                                            <input type="text" required="required" value="" maxlength="100" class="form-control" name="name" id="name">
                                        </div>
                                        <div class="col-md-6">
                                            <label>Your email address *</label>
                                            <input type="email" required="required" value="" maxlength="100" class="form-control" name="email" id="email">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <label>Comment *</label>
                                            <textarea maxlength="5000" rows="10" class="form-control" name="comment" id="comment" style="height: 138px;" required="required"></textarea>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <input type="submit" value="Post Comment" class="btn btn-primary">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>*@
                </div>
                <aside class="col-lg-3">
                    @*<div>
                            <h4>Search Games</h4>
                            <form class="search" action="#" method="Post">
                                <div class="input-group">
                                    <input class="form-control" placeholder="Search..." name="email" type="email" required="required">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="submit" name="subscribe">Go!</button>
                                    </span>
                                </div>
                            </form>
                        </div>*@
                    <div class="panel-box">
                        <div class="titles no-margin">
                            <h4>
                                High Score
                            </h4>
                        </div>
                        @foreach (var items in Model.HighScore)
                    {<br />
                        <div class="row">
                            <div class="col-md-3">
                                <img src="~/@items.UserImage" style="border-radius: 40%; height:40px;width:40px;" />
                            </div>
                            <div class="col-md-5">
                                @items.UserFullName
                            </div>
                            <div class="col-md-4">
                                @if (Model.Type == enumGameType.High_Score)
                                {
                                <div class="col-md-2" align="left">
                                    @items.HighScore
                                </div>
                                }else if (Model.Type == enumGameType.Points)
                                {
                                <div class="col-md-2" align="left">
                                    @items.Points
                                </div>
                                }else if (Model.Type == enumGameType.Level)
                                {
                                <div class="col-md-2" align="left">
                                    @items.Level
                                </div>
                                }
                            </div>
                        </div>
                        <hr />
                    }
                        <div class="row">
                            <div class="info-panel">
                                <p>
                                    The User To Maintain HighScore Today Will Receive Rs 100 Recharge Card from eSewa.
                                </p>
                                @*<p>Summary Here</p>*@
                            </div>
                        </div>
                    </div>
                    @await Component.InvokeAsync("Ads")
                    @*@await Component.InvokeAsync("Ads")
                        @await Component.InvokeAsync("Ads")*@
                </aside>
            </div>
        </div>
    </section>
    @section Scripts {
        <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5d07460b4351e90012650e92&product=' inline-share-buttons' async='async'></script>
    }

Sportsmandu/Views/Game/PlayGame.cshtml
@using Sportsmandu.Model.Entities.ViewModels;
@model Sportsmandu.Models.GameViewModel;
@{
    Layout = null;
    ViewData["Title"] = @Model.Name;
}
<title>@Model.Name</title>
<link rel="shortcut icon" type="image/x-icon" href="~/images/fav.ico">
@Html.Raw(ViewBag.GameHtml)
<script>
    var GAME_ID = '@Model.Guid';
    var GAME_SALT = '@ViewBag.Salt';
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-1428209939997083",
        enable_page_level_ads: true
    });
</script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-133838094-2"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'UA-133838094-2');
</script>
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
    var OneSignal = window.OneSignal || [];
    OneSignal.push(function () {
        OneSignal.init({
            appId: "6a6b9e8f-d432-4aa0-81e4-5b4fa1e21ac0"
        });
    });
</script>