Sportsmandu/ViewComponents/CultureViewComponent.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Sportsmandu.Model.Entities.Ground;
using System;
using System.Collections.Generic;
using System.Linq;
namespace Sportsmandu.ViewComponents
{
    [AllowAnonymous]
    public class CultureViewComponent : ViewComponent
    {
        IMemoryCache _cache;

        public CultureViewComponent(IMemoryCache cache)
        {
            _cache = cache;
        }
        public IViewComponentResult Invoke()
        {
            if (this.RouteData.Values["area"] != null && this.RouteData.Values["area"] == "Admin") return View();
            string Culture = this.RouteData.Values["culture"] != null ? this.RouteData.Values["culture"].ToString() : null;
            Culture = Culture == "1" ? Culture = "En" : Culture;
            Culture = Culture == "2" ? Culture = "Np" : Culture;
            if (Culture == null)
            {
                //var KKa= this.HttpContext.Response.Cookies;
                var rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
                var culture = rqf.RequestCulture.Culture;
                Culture = culture.Name;
                ;// return View();
            }
            var rqfa = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            var culturea = rqfa.RequestCulture.Culture;
            if (Culture.ToLower() != culturea.Name)
            {
                this.HttpContext.Features.Set<IRequestCultureFeature>(new RequestCultureFeature(new RequestCulture(culture: Culture.ToLower(), uiCulture: Culture.ToLower()), null));
                //SetCurrentThreadCulture(requestCulture)
                this.HttpContext.Response.Cookies.Append(
                    CookieRequestCultureProvider.DefaultCookieName,
                    CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(Culture)),
                    new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
                );
            }
            this.HttpContext.Items["current_culture"] = Culture.Substring(0,1).ToUpper() + Culture.Substring(1, 1);
            var _result = Sportsmandu.Api.Controllers.ProductController.SiteSectionLanguageTitle(Culture, "layout",_cache);
            if (_result == null) return View();
            //var KK = this.HttpContext.Response.Cookies;
            foreach (var items in _result)
            {
                try
                {
                    var itsValue = items.LanguageTitleGlobalizations.Where(x => x.CultureCode == Culture).SingleOrDefault();
                    this.HttpContext.Items[items.LanguageTitleName] = itsValue == null ? "ITS NULL" : itsValue.Value;
                }
                catch (Exception) { }
                //ViewData.Add(new KeyValuePair<string, object>(items.LanguageTitleName, items.LanguageTitleGlobalizations
                //            .Where(x => x.CultureCode == Culture).SingleOrDefault().Value));
            }
            //if (this.RouteData.Values["area"] != null && this.RouteData.Values["area"] != "Admin")
            {
                var news = Sportsmandu.Api.Controllers.ProductController.AllBlogPost(Culture,_cache);
                if(news != null)
                {
                    var blogPosts = news.Take(2).ToList();//_context.BlogPosts.Include(x=>x.Culture).OrderByDescending(x => x.PublishDate).Where(x=>x.Culture.Code == Culture).Take(2).ToList();
                    this.HttpContext.Items["Footer_News"] = blogPosts ;
                }
                // var resultTosend = blogPosts.Adapt<List<BlogPostViewModel>>();
            }
            List<GroundVMFORES> venues = Sportsmandu.Api.Controllers.ProductController.GetVenues(Culture).ToList();
            if (venues != null)
            {
                var blogPosts = venues.Where(x=>x.Type == enumVenueType.Venue).Take(8).ToList();//_context.BlogPosts.Include(x=>x.Culture).OrderByDescending(x => x.PublishDate).Where(x=>x.Culture.Code == Culture).Take(2).ToList();
                this.HttpContext.Items["Footer_Venues"] = blogPosts;
            }

            var associations = Sportsmandu.Api.Controllers.ProductController.GetAssociations(Culture);
            this.HttpContext.Items["association_list"] = associations;
            return View();
        }
    }
}

Sportsmandu/Views/Shared/_Contribute.cshtml
@if (!Model)
{
    <div id="Contribution" role="alert" class="alert alert-info alert-dismissible fade show" style="
                                          background-color: #fbc02d;
                                          border-color: #bee5eb;">
        @*Are you related to this Club ? Click Here <br /><br />*@
        Sports enthusiast ? Freelancer ? Looking for Some Work ? Good English ? We Are Hiring !<br /> This page is marked as incomplete ! Want to contribute the contents and earn rewards ? <a href="~/@ViewContext.RouteData.Values["Culture"]/Home/Apply">Contact Here !</a>
    </div>
}

Sportsmandu/Views/Shared/_FrontEndGallery.cshtml
<div class="tab-pane" id="gallery">

    <div class="row align-items-center">
        <div class="col-lg-4">
            <h3 v-if="selectedGallery.id === null" class="clear-title no-margin">Albums</h3>
            <h3 v-if="selectedGallery.id !== null" class="clear-title no-margin">{{selectedGallery.name}}</h3>
        </div>
        <div class="col-lg-3">            
        </div>
        <div class="col-lg-5">
            <h3 align="right" v-if="selectedGallery.id !== null" class="clear-title no-margin"><span @@click="selectedGallery.id=null">Back to Gallery</span></h3>
        </div>
    </div>
    <div class="row portfolioContainer margin-top">
        <div v-if="gallery.length == 0">
            No Gallery Found for @Model.Name .
        </div>
        <div v-if="selectedGallery.id === null" class="col-sm-6 col-lg-4 col-xl-3" v-for="gallery in gallery">
            <div class="item-gallery">
                <div class="hover small">
                    <img :src="baseUrl + gallery.thumbnail" :alt="gallery.name" @@click="selectedGallery = gallery" />
                </div>
                <div class="info-gallery">
                    <p @@click="selectedGallery = gallery">{{gallery.name}}</p>
                    <i class="fa fa-picture-o"></i>
                </div>
            </div>
        </div>
        <div v-if="selectedGallery.id !== null" class="col-sm-6 col-lg-4 col-xl-3" v-for="photo in selectedGallery.photos">
            <div class="item-gallery">
                <div class="hover small">
                    <img :src="baseUrl + photo.thumbnail" :alt="photo.name" />
                    <a class="swipebox-ligbox" :href="baseUrl + photo.thumbnail">
                        <div class="overlay"><i class="fa fa-plus"></i></div>
                    </a>
                </div>
                <div class="info-gallery">
                    <p @@click="selectedGallery = gallery">{{photo.name}}</p>
                    <i class="fa fa-picture-o"></i>
                </div>
            </div>
        </div>
    </div>
    @*@Model.Name Gallery
        @foreach (var items in Model.Gallery)
        {
            <h1>sdfdsf</h1>
        }*@
</div>

Sportsmandu/Views/Shared/_Layout.cshtml
@using Sportsmandu.Model.Entities.ViewModels;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    @{
        string Title = ViewContext.RouteData.Values["Culture"] != null ? ViewContext.RouteData.Values["Culture"].ToString() == "Np" ? "स्पोर्ट्समाण्डु" : "Sportsmandu" : "Sportsmandu";
    }
    <title>@ViewData["Title"] - @Title</title>
    <meta name="keywords" content="Sportsmandu" />
    <meta name="author" content="Syntech Engineering">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:image" content="@ViewData["OG:Image"]" />
    <meta property="og:title" content="@ViewData["Title"]" />
    <meta property="og:url" content="@ViewData["og:url"]" />
    <meta property="og:site_name" content="Sportsmandu" />
    <meta property="og:description" content="@ViewData["og:description"]" />
    <meta property="og:type" content="@ViewData["og:type"]" />
    <meta property="fb:app_id" content="2086666778115750" />
    <link href="~/assets/css/main.css" rel="stylesheet" media="screen">
    <link rel="shortcut icon" type="image/x-icon" href="~/images/fav.ico">
    <link rel="apple-touch-icon" href="~/img/icons/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/img/icons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/img/icons/apple-touch-icon-114x114.png">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1428209939997083",
            enable_page_level_ads: true
        });
    </script>
</head>
<body>
<h1 hidden>Jobs Abroad , Games Online , Cool Jobs , Games Download , Find Jobs , Sports Jobs</h1>
@if (@ViewData["ToastrMessage"] != null)
{
    @: toastr.error('@ViewData["ToastrMessage"]');
}
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=1373568719321446&autoLogAppEvents=1"></script>
<div id="sportsSignalR">

</div>
<div id="sportsManduMainPage">
    <div id="layout">
        <partial name="_CookieConsentPartial"/>
        <partial name="_header"/>
        @RenderBody()
    </div>
</div>
<script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
<environment names="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.2/vue.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.js"></script>
</environment>
<environment names="Staging,Production"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.2/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
</environment>
@*<script src="https://sportsmandu.com/aspnet/signalr/dist/browser/signalr.js"></script>*@
<script src="~/aspnet/signalr/dist/browser/signalr.js"></script>
<script type="text/javascript" src="~/assets/js/popper.min.js" asp-append-version="true"></script>
<script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
<script type="text/javascript" src="~/assets/js/theme-scripts.js" asp-append-version="true"></script>
<script type="text/javascript" src="~/assets/js/theme-main.js" asp-append-version="true"></script>
<environment names="Development">
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/siteSignalR.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/siteSignalR.min.js" asp-append-version="true"></script>
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
        var OneSignal = window.OneSignal || [];
        OneSignal.push(function() {
            OneSignal.init({
                appId: "6a6b9e8f-d432-4aa0-81e4-5b4fa1e21ac0",
            });
        });
    </script>
</environment>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-133838094-2"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() { dataLayer.push(arguments); }

    gtag('js', new Date());

    gtag('config', 'UA-133838094-2');
</script>
<script src="https://cdn.jsdelivr.net/momentjs/2.10.6/moment-with-locales.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" async="">
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" async=""></script>
@try
{
    @if (@ViewContext.RouteData.Values["Culture"] != null && @ViewContext.RouteData.Values["Culture"].ToString() == "Np")
     {
         <script>
             moment.locale("ne");
         </script>
     }
}
catch (Exception ex)
{

}
<script>
    jQuery(document).ready(function($) {
        setTimeout(function() {
                var now = moment();
                $('time').each(function(i, e) {
                    var time = moment($(e).attr('datetime'));
                    if (now.diff(time, 'days') <= 1) {
                        $(e).html('<span>' + time.from(now) + '</span>');
                    } else {
                        $(e).html('<span>' + moment(time).format('LL') + '</span>');
                    }
                });
            },
            2000)
    });
</script>
<partial name="_footer"/>
</body>
</html>
<style>
    .blink {
        width: 200px;
        height: 50px;
        background-color: magenta;
        padding: 15px;
        text-align: center;
        line-height: 50px;
    }

    .blinkingtext {
        font-size: 25px;
        font-family: cursive;
        color: black;
        animation: blink 1s linear infinite;
    }

    @@keyframes blink {
        0% {
            opacity: 0;
        }

        50% {
            opacity: .5;
        }

        100% {
            opacity: 1;
        }
    }
</style>

<style>
    .profile_image {
        padding-top: 5px !important;
        width: 45px;
        height: 45px;
        border-radius: 50%;
        overflow: hidden;
        margin: 0 auto;
    }

    .profile_image {
        padding-top: 5px !important;
        width: 45px;
        height: 45px;
        border-radius: 50%;
        overflow: hidden;
        margin: 0 auto;
    }

    .prediction-image {
        width: 30%;
        height: 90px;
        padding: 20px;
    }

        .prediction-image:hover {
            border: dashed;
            border-color: sandybrown;
        }

    .blink {
        width: 200px;
        height: 50px;
        background-color: magenta;
        padding: 15px;
        text-align: center;
        line-height: 50px;
    }

    .blinkingtext {
        font-size: 25px;
        font-family: cursive;
        color: black;
        animation: blink 1s linear infinite;
    }

    @@keyframes blink {
        0% {
            opacity: 0;
        }

        50% {
            opacity: .5;
        }

        100% {
            opacity: 1;
        }
    }

    .drawclass {
        width: 100%;
        align-content: center;
    }
</style>
@Html.Partial("_adminMessage");
<script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.9.3/intro.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.9.3/introjs.min.css" rel="stylesheet" media="screen">
<script>
    sportsmanduApp.currentCulture = '@ViewContext.RouteData.Values["Culture"]';
</script>
@if (ViewBag.Matches != null)
    {
<script>
        sportsmanduApp.allMatches = @Html.Raw(Json.Serialize(((List<Sportsmandu.Models.League.SeasonMatchViewModel>)ViewBag.Matches)));
</script>
    }

@if (ViewBag.MyPredictions != null)
    {
        <script>
            sportsmanduApp.myPredictions = @Html.Raw(Json.Serialize(((List<Sportsmandu.Models.PredictionVMFORES>)ViewBag.MyPredictions)));
        </script>
        }
@*<script>
    $(document).ready
        (function () {
            alert("Here");
            //setTimeout(function () {
            //    introJs().start();
            //}, 3000);
            //setTimeout(function () {
            //    $('#adminMessage').modal('show');
            //}, 1000 * 60 * 2);
        });
</script>*@
@RenderSection("Scripts", required: false)

Sportsmandu/Views/Shared/_Layout_Backup.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sportsmandu</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sportsmandu</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Sportsmandu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Sportsmandu/Views/Shared/_adminMap.cshtml
<div>
    <span>Feel Free To Edit The @ViewContext.RouteData.Values["Controller"] ! All Post Need To Go Through Verifications !</span>
</div>

<style>

    #map {
        width: 100%;
        height: 550px;
        z-index: 100;
    }

    #mapSearchContainer {
        position: fixed;
        top: 20px;
        right: 40px;
        height: 30px;
        width: 180px;
        z-index: 110;
        font-size: 10pt;
        color: #5d5d5d;
        border: solid 1px #bbb;
        background-color: #f8f8f8;
    }

    .pointer {
        position: absolute;
        top: 86px;
        left: 60px;
        z-index: 99999;
    }
</style>

Sportsmandu/Views/Shared/_descriptionEditor.cshtml
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jodit/3.1.92/jodit.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/jodit/3.1.92/jodit.min.js"></script>
<script>
	alert("Loading Desc Editor")
	setTimeout(function () {
		$('textarea').each(function () {
			var editor = new Jodit(this);
			editor.value = '@Model.Description';
		});
	}, 3000);
</script>

Sportsmandu/Views/Shared/_gallery.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager    
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css" />
<button type="button" class="btn btn-send" data-toggle="modal" data-target="#myGallery" @@click="loadGallery()">Gallery</button>
<div class="modal" id="myGallery">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Gallery !!</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <button type="button" class="btn btn-primary" @@click="addGallery()">
                    Add Album
                </button>
                <div>                    
                    <div v-for="(gallery,id) in myGallery" :key="id" @@click="myGalleryPhotos= []; selectedGallery = gallery;initDropZone();loadGalleryImages()">
                        <input type="text" v-if="id == galleryIndexEdit" v-model="gallery.name" />
                        <button type="button" v-if="id == galleryIndexEdit" class="btn btn-default" @@click="saveGallery(gallery)">Save</button>
                        <h3><span v-if="id !== galleryIndexEdit && selectedGallery == gallery || selectedGallery == null">{{gallery.name}}</span> <span style="background-color:red" @@click="deleteGallery(gallery.id)">Delete</span></h3>
                    </div>
                        <span v-if="selectedGallery != null" @@click="selectedGallery = null">Back</span>
                </div>
                <div v-if="selectedGallery != null">
                    <div id="myDropZone" class="dropzone">
                    </div>
                    <div v-if="myGalleryPhotos != null" class="col-md-12">
                        <div v-for="images in myGalleryPhotos">                            
                            <img :src="baseUrl + images.thumbnail" style="width:150px" />
                            <span @@click="deleteGalleryPhotos(images.id)" style="background-color:red">Delete</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">                
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Sportsmandu/Views/Shared/_header.cshtml
<header>
    <div class="headerbox">
        <div class="container">
            <div class="row justify-content-between align-items-center">                
                <div class="col">
                    <div class="logo">
                        @{
                            string Message = string.Empty;
                           Message= ViewContext.RouteData.Values["Culture"] != null ?  ViewContext.RouteData.Values["Culture"].ToString() : "Np";
                        }
                        <a href="~/@Message/Home/Construction" title="Return Home">
                            <img src="~/images/logo.png" alt="Logo" class="logo_img img-responsive">
                        </a>
                    </div>
                </div>
                <div class="col" style="padding-left: 15%;height: 80px;">
                    <div class="adds">
                        <a href="https://redbull.com" target="_blank">
                            <img src="http://www.stickpng.com/assets/images/580b57fcd9996e24bc43c1e8.png" alt="" class="img-responsive logo_img" style="height: 80px;">
                        </a>
                    </div>                    
                </div>
                <div class="col" align="right">
                    <div class="adds">
                        <a href="https://samsung.com" target="_blank">
                            <img src="~/images/Advt/samsung.png" alt="" class="img-responsive logo_img" style="height: 80px;">                            
                        </a>
                    </div>
                    <a class="mobile-nav" href="#mobile-nav"><i class="fa fa-bars"></i></a>                    
                </div>
            </div>
        </div>
    </div>
</header>
<partial name="_menu" />

Sportsmandu/Views/Shared/_menu.cshtml
<nav class="mainmenu">
    <div class="container">
        <ul class="sf-menu" id="menu">
            <li class="current"><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/Construction">@this.Context.Items["menu_home"]</a></li>
            <li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/FbPredictions">@this.Context.Items["menu_predictions"]</a></li>
            <li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/News">@this.Context.Items["menu_news"]</a></li>
            @*<li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/Game">Online Games</a></li>*@
            <li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/Contact">@this.Context.Items["menu_contact_us"]</a></li>
            <partial name="_LoginPartial" />
            @*<cache expires-after="@TimeSpan.FromMinutes(5)">*@
            <li class="right">@await Component.InvokeAsync("Culture")</li>
            @*</cache>*@

        </ul>
    </div>
</nav>
<div id="mobile-nav">
    <ul>
        <li class="current"><a href="~/@ViewContext.RouteData.Values["Culture"]/Home">@this.Context.Items["menu_home"]</a></li>
        <li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/FbPredictions">@this.Context.Items["menu_predictions"]</a></li>
        <li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/News">@this.Context.Items["menu_news"]</a></li>
        @*<li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/Game">Online Games</a></li>*@
        <li><a href="~/@ViewContext.RouteData.Values["Culture"]/Home/Contact">@this.Context.Items["menu_contact_us"]</a></li>
        <partial name="_LoginPartial" />
    </ul>    
</div>

Sportsmandu/Views/Shared/_search.cshtml
<div class="our-products-section our-products-page sec-spacer">
			<div class="container">
				<div class="row">	                
                    <a href="~/Admin/@(ViewContext.RouteData.Values["Culture"] == null ? "1":ViewContext.RouteData.Values["Culture"])/@ViewContext.RouteData.Values["Controller"]/Create" class="btn-send">Create New</a>
	<a href="~/Admin/2/@ViewContext.RouteData.Values["Controller"]/ToBeTranslated" class="btn-send">Translate</a> <a href="~/Admin/@ViewContext.RouteData.Values["Controller"]/Verify" class="btn-send">Verify</a> 
	<BR><BR>
<form action="/Admin/@ViewContext.RouteData.Values["Controller"]/Search/" class="ui form" enctype="multipart/form-data" method="post">
                        @Html.AntiForgeryToken()
						<div class="col-md-12 col-sm-12 col-xs-12">    
							<div class="form-group">
								<label class="title-bg">Search @ViewContext.RouteData.Values["Controller"]</label>
								<input name="Term" class="form-control" type="text">
							</div>
						</div>
                    </form>
					</div>
					</div>
					</div>